name: build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * 2"


jobs:
  build-push-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: jonakoudijs/youtube-download-config:latest
      - name: Push Image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: jonakoudijs/youtube-download-config:latest
