name: Keepalive Workflows
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create-keepalive-commit:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Keepalive Commit
        uses: gautamkrishnar/keepalive-workflow@v2
